### ISSUE TITLE
Amazon Linux needs a template or to use another template

### ISSUE THREAD

**Issue by kjhosein** [example42/puppet-timezone#11]
`facter` on an Amazon Linux instance reports `operatingsystem` as 'Amazon'. There is no template called 'timezone-Amazon'. 

Since Amazon Linux is essentially a Red Hat variant, I'd be happy if it got the 'timezone-RedHat' template.

**Comment by alvagante** [comment]
PR welcomed, in the shape you suggested

**Comment by MichaelGooden** [comment]
This issue can be closed.
